baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Petras Stuff'
theme = 'github-style'

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
email = 'petreh9is@gmail.com'
github = 'Kayigis'
description = 'wazzaa'
author = 'Petra'
location = 'Wakanda'
